<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <UserSecretsId>979329a4-225e-4181-812d-d11a35559575</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..</DockerfileContext>
    <DockerComposeProjectPath>..\..\docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.SqlServer" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Modules\Subscriptions\Billora.Subscriptions.Application\Billora.Subscriptions.Application.csproj" />
    <ProjectReference Include="..\Modules\Subscriptions\Billora.Subscriptions.Infrastructure\Billora.Subscriptions.Infrastructure.csproj" />
  </ItemGroup>
</Project>
